name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup ESLint
        run: |
          npm install --save-dev eslint eslint-plugin-react@^7.21.5 @typescript-eslint/eslint-plugin@latest eslint-config-airbnb@latest eslint-plugin-import@^2.22.1 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-react-hooks@^4 @typescript-eslint/parser@latest eslint-import-resolver-typescript eslint-config-prettier eslint-plugin-prettier
          [ -f .eslintrc.json ] || wget https://raw.githubusercontent.com/gvgesanto2/linters-config/main/react-typescript/.eslintrc.json
          [ -f .eslintignore ] || wget https://raw.githubusercontent.com/gvgesanto2/linters-config/main/react-typescript/.eslintignore
          [ -f tsconfig.json ] || wget https://raw.githubusercontent.com/gvgesanto2/linters-config/main/react-typescript/tsconfig.json
      - name: ESLint Report
        run: npx eslint .
  stylelint:
    name: Stylelint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x stylelint-config-prettier-scss
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/gvgesanto2/linters-config/main/react-typescript/.stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.scss"
  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi
